# Install & Configure Zabbix Agent in Passive Mode on Centos
# Reference: https://www.zabbix.com/download?zabbix=6.0&os_distribution=centos&os_version=8&components=agent&db=&ws=

- name: "Install & Configure Zabbix Agent (Passive)"

  hosts: zabbixProxy

  gather_facts: true

  vars:
    ZABBIX_REPO_URL: "https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm"
    
    # Incase of Zabbix Proxy, Change this IP to the Proxy Server IP
    ZABBIX_SERVER_IP: "127.0.0.1"

  tasks:
    - name: "Install Zabbix Repository"
      yum:
        name: "{{ ZABBIX_REPO_URL }}"
        state: present

    - name: "Install Zabbix Agent"
      yum: 
        name: zabbix-agent
        state: present

    - name: "Start zabbix-agent service"
      service:
        name: zabbix-agent
        state: started
        enabled: true

    - name: "Update Zabbix Server IP in the Agent Config file"
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        after: 'Passive checks related'
        regexp: '^Server=[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
        replace: "Server={{ ZABBIX_SERVER_IP }}"

      notify: restart_zabbix_agent

    - name: "Enabling Remote Command in Agent Config file"
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        after: 'Option: DenyKey'
        regexp: '^# DenyKey=system.run\[\*\]'
        replace: 'AllowKey=system.run[*]'

      notify: restart_zabbix_agent

  handlers:
    - name: restart_zabbix_agent
      service:
        name: zabbix-agent
        state: restarted
