# Uninstall Zabbix Agent from Centos

- name: "Uninstall Zabbix Agent"

  hosts: zabbixProxy

  gather_facts: false

  tasks:

    - name: "Uninstall Zabbix Agent"
      yum:
        name: zabbix-agent
        state: absent

    - name: "Remove Zabbix Agent Config file"
      file:
        path: /etc/zabbix/zabbix_agentd.conf
        state: absent
