# Updating Zabbix Agent 2 Config file to Allow 'system.run' Item key

- name: "Configure Zabbix Agent 2 AllowKey Parameter"

  hosts: all

  gather_facts: false

  tasks:

    - name: "Enabling Remote Command in Agent Config file"
      replace:
        path: /etc/zabbix/zabbix_agent2.conf
        after: 'Option: DenyKey'
        regexp: '^# DenyKey=system.run\[\*\]'
        replace: 'AllowKey=system.run[*]'

      notify: restart_zabbix_agent

  handlers:
    - name: restart_zabbix_agent
      service:
        name: zabbix-agent2
        state: restarted
